image: golang:latest

stages:
  - build
  - test
  - deploy

# Share cache across all jobs
cache:
  key: gopath
  paths:
    - .gopath

before_script:
  - mkdir -p .gopath/bin
  - export GOPATH=$(pwd)/.gopath
  - export PATH=$GOPATH/bin:$PATH

build:
  artifacts:
    expire_in: 1 week
    paths: binaries
  stage: build
    - export GOARCH=amd64
    - declare -A extensions=()
    - extensions["windows"]=".exe"
    - [ "${CI_COMMIT_TAG:-x}" != "x" ] && VER=${CI_COMMIT_TAG}  || VER=${CI_COMMIT_SHORT_SHA}
    - [ "${CI_COMMIT_TAG:-x}" != "x" ] && TAG=latest || VER=nightly
    - mkdir binaries
    - |
      for os in linux windows darwin; do
        GOOS=$os go build -o gql"${extensions[${os}]}" main.go
        tar zcf gql-${os}-${GOARCH}-${VER}.tar.gz gql
        tar zcf gql-${os}-${GOARCH}-${TAG}.tar.gz gql
      done
    - mv gql-*.tar.gz binaries

test:
  stage: build
  script:
    - go test ./...

deploy:
  image: garland/docker-s3cmd
  stage: deploy
  only:
    - master
    - tags
  script: |
    for f in binaries/*; do
      s3cmd --access-key ${ACCESS_KEY_ID} --secret ${SECRET_ACCESS_KEY} -P --region ${S3_REGION} --host ${S3_ENDPOINT} cp $f s3://${BUCKET}/$f
    done